language: java
sudo: true
dist: trusty
jdk: oraclejdk8

before_script:
  - psql -c 'create database famec' -U postgres
  
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
