language: java
sudo: true
dist: trusty
jdk: oraclejdk8

before_script:
  - psql -c 'create database famec' -U postgres
  
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  
deploy:
  provider: heroku
  api_key:
    secure: d0511a96-852c-45b6-b95d-c9397843551d
